name: Test Actions

on: push

jobs:
  test:
    name: Test Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: github/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
