name: 'Frontend: Action'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
#        run: |
#          git fetch --no-tags --depth=1 origin master
#          git checkout -b master
#          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm

      - name: Configure Git to use HTTP
        run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/


      - name: Install
        run: cd Frontend/online-resume && npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v14
        with:
          config_path: "/Frontend/online-resume/.eslintrc"
          ignore_path: "/Frontend/online-resume/.eslintignore"
          extra_args: "--max-warnings=0"
          file_extensions: |
            **/*.ts
            **/*.tsx

      - name: Test files
        run: cd Frontend/online-resume && npm run test
